[build]
command = """
pip install -r requirements.txt
"""
publish = "public"
functions = "functions"

[build.environment]
PYTHON_VERSION = "3.11.0"
NODE_VERSION = "18"

[[redirects]]
from = "/"
to = "/.netlify/functions/app"
status = 200

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
directory = "functions"
node_bundler = "esbuild"

[dev]
publish = "public"
functions = "functions" 