[build]
publish = "public"
command = """
pip install --upgrade pip
pip install -r requirements.txt
"""

[build.environment]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18"

[functions]
directory = "functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200 