[build]
publish = "public"
command = """
mkdir -p functions
cp -r functions/* functions/
pip install -r functions/requirements.txt
"""

[build.environment]
PYTHON_VERSION = "3.11.0"
NODE_VERSION = "18"

[functions]
directory = "functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200 