[build]
command = "pip install -r requirements.txt"
publish = "public"

[build.environment]
PYTHON_VERSION = "3.11.0"

[[redirects]]
from = "/*"
to = "/.netlify/functions/app"
status = 200

[functions]
external_node_modules = [] 